name: Expo Android

on:
  push:
  pull_request:
      branches:
          - master
jobs:
  Build-Android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Install deps
        run: yarn install

      - name: Build Android APK Bundle
        run: yarn build-android
