name: frontend
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn

      - name: Run linter
        working-directory: ./
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn

      - name: Run tests
        working-directory: ./
        run: yarn test
