name: Continuous Deployment

on: push

jobs:
  deploy-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.21.0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn
        
      - name: Install Expo
        working-directory: ./
        run: yarn add global expo-cli@3.13.1
        
      - name: Eject Expo
        working-directory: ./
        run: yarn eject
        
      - name: Remove old keystore
        working-directory: ./android/app
        run: rm -rf debug.keystore

      - name: Generate new keystore
        working-directory: ./android/app
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" -keypass android -keyalg RSA -keysize 2048 -validity 10000

#       - name: Remove build.gradle
#         working-directory: ./android
#         run: rm -rf build.gradle

#       - name: Create build.gradle
#         working-directory: ./android
#         run: TODO

      - name: Elevate Permission
        working-directory: ./android
        run: chmod 777 ./gradlew

      - name: Build application
        working-directory: ./android
        run: ./gradlew assembleDebug
      
      - name: Upload APK
        working-directory: ./android
        run: fileurl=$(curl --upload-file ./app-debug.apk https://transfer.sh | tail -1)
        
      - name: Get download URL
        working-directory: ./android
        run: get_file_url=$(echo $fileurl | cut -d'/' -f 4- | xargs printf 'https://transfer.sh/get/%s')
        
      - name: Upload APK
        working-directory: ./android
        run: curl -d "url=$get_file_url" -d "platform=android" -X POST "https://${{secrets.APPETIZE_API_TOKEN}}@api.appetize.io/v1/apps/yhuygk387qhwdrp51pr673jz8g"
