name: frontend

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn

      - name: Run linter
        working-directory: ./
        run: yarn lint

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn

      - name: Generate keystore
        working-directory: ./android/app
        run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -dname "cn=Unknown, ou=Unknown, o=Unknown, c=Unknown" -keypass android -keyalg RSA -keysize 2048 -validity 10000

      - name: Elevate Permission
        working-directory: ./android
        run: chmod 777 ./gradlew

      - name: Build application
        working-directory: ./
        run: yarn build-android

  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Check out repository
  #       uses: actions/checkout@v2

  #     - name: Set up Node
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12

  #     - name: Cache dependencies
  #       uses: actions/cache@v2
  #       with:
  #         path: client/node_modules
  #         key: ${{ runner.os }}-cache

  #     - name: Install dependencies
  #       working-directory: ./
  #       run: yarn

  #     - name: Install POD dependencies
  #       working-directory: ./ios
  #       run: pod install

  #     - name: Build application
  #       working-directory: ./
  #       run: yarn build-ios

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-cache

      - name: Install dependencies
        working-directory: ./
        run: yarn

      - name: Run tests
        working-directory: ./
        run: yarn test
