build-IOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64
      - uses: sinoru/actions-setup-xcode@v1.1.2
        with:
          xcode-version: '11.2.1'
          apple-id: ${{ secrets.EXPO_APPLE_ID }}
          apple-id-password: ${{ secrets.EXPO_APPLE_PASSWORD }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Install deps
        run: yarn install

      - name: Build iOS app
        run: yarn build-ios
        env:
            EXPO_APPLE_ID: ${{secrets.EXPO_APPLE_ID}}
            EXPO_APPLE_ID_PASSWORD: ${{secrets.EXPO_APPLE_PASSWORD}} 
